path_classifiers:
  test:
    - exclude: /
    - test
    - exclude: test/data
  library:
    - ext

queries:
  # Start by hiding the results of all queries.
  - include: "*"

extraction:
  cpp:
    configure:
      command:
        - meson -Dtests=enabled build
    index:
      build_command:
        - ninja -C build
