path_classifiers:
  test:
    - exclude: /
    - test
    - exclude: test/data
  library:
    - ext

queries:
  - include: "*"

extraction:
  cpp:
    prepare:
      packages:
        - clang-9
    after_prepare:
      - export CXX=clang++-9
    configure:
      command:
        # lgtm ships meson version 0.51.2 which doesn't support fs module
        # needed for generating tests file in test/meson.build
        - meson -Dtests=disabled build
    index:
      build_command:
        - ninja -C build
