path_classifiers:
  test:
    - exclude: /
    - test
    - exclude: test/data
  library:
    - exclude: include/args.hxx

queries:
  # Start by hiding the results of all queries.
  - exclude: "*"
  - include:
      tags:
        - "security"
        - "correctness"
      severity: "error"

extraction: 
  cpp:
    configure:
      command:
        - meson -Dtests=enabled build
    index:
      build_command:
        - ninja -C build
