name: Run Unittests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        compiler: [clang++-8, clang++-9, g++-9]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install compiler and dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          compiler=${{ matrix.compiler }}
          compiler=${compiler/clang++/clang}
          sudo apt-get install --force-yes ${compiler}
          pip3 install meson

      - name: Build using meson
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          meson --unity on -Dtests=enabled -Db_lundef=false \
          -Db_sanitize=address,undefined build && \
          ninja -C build

      - name: Run meson tests
        run: ASAN_OPTIONS=detect_odr_violation=0 ninja -C build test
